name: Lint and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: master

    - name: Build
      run: zig build

  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: master

    - name: Lint
      run: zig fmt --check src/*.zig

  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: master

    - name: Test
      run: zig build test
